### PR TITLE
environment-creation

### PR DESCRIPTION
**Pull request by nviolante25**
# Environment

Solves #1 

- [x]  Add Pendulum wrapper from openai-gym to dm-env
- [x] Add simple interaction loop with random actions
- [ ] Add interaction with simple Agent. See related PR #6 that spans from this branch.

### CODE REVIEW

**Comment by theovincent** [comment]
I did not test the code on my computer yet but it seems nice! I would just suggest renaming `scr` by `ppo` so that we can import functions with
```Python
from ppo.env-wrapper.pendulum_wrapper import PendulumEnv
```
and not 
```Python
from scr.env-wrapper.pendulum_wrapper import PendulumEnv
```

And maybe changing `env-wrapper` to `env_wrapper` to have a consistent naming convention :)

**Comment by nviolante25** [comment]
Hi! Thanks or your comment

- Regarding the first issue, the `src` folder is typically used to stored all the code within the project, so we'll never do something like `from src.some_folder import something` because we'll never be outside the `src` folder. This way other kind of stuff, like plots and metrics (or whatever) can be stored in a separate folder with the same level of `hierarchy` as `src`. However, we can just delete `src` and have everything under the repo folder `ppo`. 

- I'll change the name of the `env-wrapper` folder, good catch!

**Comment by theovincent** [comment]
I see what you mean. I wanted to use a `setup.py` file so that the import are coming from the highest level each time and they do not depend on the relative position of the files. For example, in the repository of [dm_env](https://github.com/deepmind/dm_env) they call a folder `dm_env` that represents the `scr` for you. This allows them to import functions when they are in the folder `dm_env` as if they would be outside for example [here](https://github.com/deepmind/dm_env/blob/abee135a07cc8e684173586dc8a20e696bbd40fb/dm_env/auto_reset_environment.py#L25). I might not be 100% clear, we can have a quick call to speak about it if you want :)

**Comment by theovincent** [comment]
Other than that the  code is working fine for me.

**Comment by theovincent** [comment]
In the meeting that we did yesterday, we agreed on working with _InvertedPendulum_ and _Reacher_. [Here](https://github.com/emasquil/ppo/blob/ec3514e1e78f3fca9a56c4c1851e622e8c3e256e/src/env-wrapper/pendulum_wrapper.py#L11) you are defining the _Pendulum_ environment. I think it is fine and we can start like that since it should be easier

**Comment by emasquil** [comment]
I agree with @theovincent that changing the name of the directory `src` to `ppo` makes sense, especially having in mind that we'll create a package.

Other than that, the code is correct. After the renaming I'll approve the PR

**Review by emasquil — APPROVED** [review]

**Review by theovincent — APPROVED** [review]

**Review by paulinesert — COMMENTED** [review]
Hi !  I have a question : shouldn't the x and y position also be bounded ? cf the doc @theovincent provided in the tutorial : https://www.gymlibrary.ml/pages/environments/classic_control/pendulum

**Comment by nviolante25** [comment]
Hi, with the `BoundedArray` class you can only bound the whole array, not each component separately. So with the range (-8, 8) we cover all coordinates.

**Review by paulinesert — APPROVED** [review]

**Pull request merged**
